<?php

namespace SR\BlogBundle\Repository;

use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;
use Doctrine\ORM\EntityRepository;



/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository implements UserLoaderInterface
{
    public function loadUserByUsername($firstname)
    {
        return $this->createQueryBuilder('u')
            ->where('u.firstname = :firstname OR u.mail = :mail')
            ->setParameter('firstname', $firstname)
            ->setParameter('mail', $firstname)
            ->getQuery()
            ->getOneOrNullResult();
    }
}

