# app/config/security.yml

security:
  encoders:
    SR\BlogBundle\Entity\User:
      algorithm: bcrypt

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
#    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  providers:
    main:
      entity:
        class: SRBlogBundle:User
        property: username


  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
# On crée un pare-feu uniquement pour le formulaire
    main_login:
    # Cette expression régulière permet de prendre /login (mais pas /login_check !)
      pattern:   ^/login$
      anonymous: true # On autorise alors les anonymes sur ce pare-feu
    main:
      pattern:   ^/
      anonymous: true
      http_basic: ~
      provider:  main
      form_login:
        login_path: login
        check_path: login_check
        default_target_path: /article
      logout:
        path:       logout
        target:     /article






  access_control:
#    - { path: ^/admin, roles: IS_AUTHENTICATED_ADMIN }
